import './globals.css'
import { Inter } from 'next/font/google'
import {WebSocketProvider} from '../context/WebSocketContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <WebSocketProvider>
        <div className="container">{children}</div>
       </WebSocketProvider>
        </body>
    </html>
  )
}
